config/routes.rb
Rails.application.routes.draw do
  get 'search' => 'searches#search'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end



  validates :title, presence: true
  validates :body, presence: true, length: { maximum:200 }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # nameのバリデーション
  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :followed_id, dependent: :destroy
  has_many :followings, through: :passive_relationships, source: :follower

  def followed_by?(user)
      passive_relationships.find_by(follower_id: user.id).present?
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end


  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # ログイン前はトップページ以外にアクセスしてもログイン画面にリダイレクト
  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  # ログイン後に遷移するpathを設定
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

Refile.secret_key = '003673c3dbee64d7fc711edde3f618b7b4b59edf5c301ec65c524a58ac53a648da9676152ce4aa79c7b124ca99237683502191a19a9cbc005527101887947906'

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    if @comment.save
    render :comment
    else
    render 'books/show'
    end
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    @book = Book.find(params[:book_id])
    render :comment
  end



  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @user = User.find(current_user.id)
    @new = Book.new
    @books = Book.all
  end

  def show
    @new = Book.new
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @book_comment = BookComment.new
  end

  def create
    @new = Book.new(book_params)
    @new.user_id = current_user.id
    if @new.save
  # 投稿詳細へリダイレクト
    redirect_to book_path(@new), notice: 'You have created book successfully.'
    else
    @user = User.find(current_user.id)
    @books = Book.all
    render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

   def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    # 投稿詳細ページへのリンク
    redirect_to book_path(@book), notice: 'You have updated book successfully.'
    else
     render :edit
    end
   end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    # 投稿一覧にリンク
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    follow = current_user.active_relationships.new(followed_id: params[:user_id])
    follow.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    follow = current_user.active_relationships.find_by(followed_id: params[:user_id])
    follow.destroy
    redirect_back(fallback_location: root_path)
  end


end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
   @range = params[:range]
   @word = params[:word]
  if @range == "User"
     @users = User.looks(params[:search], params[:word])
  else
     @books = Book.looks(params[:search], params[:word])
  end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @new = Book.new
    @books = @user.books.page(params[:page]).reverse_order
  end

  def index
   @users = User.all
   @user = User.find(current_user.id)
   @new = Book.new
  end

   def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user.id)
    end
   end

   def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    # マイページへのリンク
     redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
     render :edit
    end
   end

   def follows
    user = User.find(params[:id])
    @users = user.followers
   end

   def followers
    user = User.find(params[:id])
    @users = user.followings
   end

   private

   def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_book_comment.html.erb
 <% book.book_comments.each do |book_comment| %>
  <table>
   <tr>
    <td>
     <%= link_to user_path(book_comment.user_id) do %>
      <p class="mx-0" style="width: auto; height: auto;">
      <%= attachment_image_tag book_comment.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg", size:'50x50' %>
      </p>
     <% end %>
     <%= link_to book_comment.user.name, user_path(book_comment.user_id) %>
     </td>
     <td>
      <%= book_comment.comment %>
     </td>
     <td>
     <!--削除-->
      <% if book_comment.user == current_user %>
       <div class="comment-delete">
       <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment),  method: :delete, remote: true, class:'btn btn-danger text-light', type:'button', "data-confirm" => "本当に削除しますか？" %>
      <% end %>
       </div>
     </td>
   </tr>
  </table>
 <% end %>

app/views/book_comments/_new_comment.html.erb
<%= form_with(model:[book, book_comment]) do |f| %>
 <%= f.text_area :comment, placeholder: "コメント", size:"90" %><br/>
 <%= f.submit "送信" %>
<% end %>

app/views/book_comments/comment.js.erb
$("#book_comment").html("<%= j(render partial: 'book_comments/book_comment', locals: {book: @book}) %>");
$("textarea").val('');

app/views/books/edit.html.erb
<!--エラーメッセージ-->
<%= render 'layouts/error', book: @book %>
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h1>Editing Book</h1>
   <%= form_with model:@book, local:true do |f| %>
   <div class="form-group">
    <label for="inputTitle">Title</label><br/>
     <%= f.text_field :title, autofocus: true, id:"inputTitle", placeholder:"タイトル"%>
   </div>
   <div class="form-group">
    <label for="inputBody">Opinion</label><br/>
    <%= f.text_field :body, autofocus: true, id:"inputBody", placeholder:"本文"%>
   </div>
   <div class="form-group">
   <%= f.submit "Update Book", class:'btn btn-success btn-sm text-light', type:'submit' %>
   </div>
   <% end %>

<!--投稿詳細・投稿一覧へのリンク-->
   <div>
    <%= link_to "Show", book_path, class:"link-primary" %>
    |
    <%= link_to "Back", books_path, class:"link-primary" %>
   </div>
  </div>
 </div>
</div>

app/views/books/index.html.erb
<!--エラーメッセージ-->
<%= render 'layouts/error', book: @new %>

<div class="container px-5 px-sm-0">
 <div class="row">
 <!--部分テンプレ-->
  <div class="col-md-3">
   <%= render 'layouts/info', user: @user %>
   <%= render 'layouts/new', new: @new %>
  </div>

<!--投稿一覧-->
  <div class="col-md-8 offset-md-1">
   <h2>Books</h2>
   <table class="table">
    <thead>
     <tr>
      <th>

      </th>
      <th>
       Title
      </th>
      <th>
       Opinion
      </th>
     </tr>
    </thead>

    <tbody>
    <% @books.each do |book| %>
     <tr>
    <!--トプ画-->
    <!--トプ画からユーザーホームへリンク-->
      <td>
       <%= link_to user_path(book.user_id) do %>
        <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
       <% end %>
      </td>
    <!--本のタイトル-->
    <!--タイトルから投稿詳細にリンク-->
      <td>
       <%= link_to book.title, book_path(book) %>
      </td>
    <!--本文-->
      <td>
       <%= book.body %>
      </td>
      <!--いいね-->
      <td>
       <div id="favorites_buttons_<%= book.id %>">
        <%= render 'favorites/favorite', book: book %>
       </div>
      </td>
      <!--コメント数-->
      <td>
       <p><%= link_to "コメント数:#{book.book_comments.count}", book_path(book.id) %></p>
      </td>
     </tr>
    <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
 <div class="row" >
  <div class="col-md-3">
  <!--部分テンプレ-->
   <%= render 'layouts/info', user: @user %>
   <%= render 'layouts/new', new: @new %>
  </div>

  <div class="col-md-8 offset-md-1" >
    <h2>Book detail</h2>
    <table class="table" >
     <tbody>
      <tr>
      <!--トプ画とユーザーネーム-->
      <!--トプ画とユーザーネームからマイページへリンク-->
       <td>
        <%= link_to user_path(@book.user_id) do %>
         <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
        <% end %><br/>
        <%= link_to @book.user.name, user_path(@book.user_id) %>
       </td>

      <!--本のタイトル-->
      <!--タイトルから投稿詳細へリンク-->
       <td>
        <%= link_to @book.title, book_path(@book) %>
       </td>

      <!--本文-->
       <td>
        <%= @book.body %>
       </td>

      <!--いいね-->
       <td>
       <div id="favorites_buttons_<%= @book.id %>">
        <%= render 'favorites/favorite', book: @book %>
       </div>
       </td>

      <!--コメント数-->
       <td>
        <p>コメント数:<%= @book.book_comments.count %></p>
       </td>

      <!--投稿編集・削除リンク-->
      <% if @book.user == current_user %>
       <td>
        <%= link_to "Edit", edit_book_path(@book), class:'btn btn-success text-light', type:'button' %>
       </td>
       <td>
        <%= link_to "Destroy", book_path(@book), method: :delete, class:'btn btn-danger text-light', type:'button', "data-confirm" => "本当に削除しますか？" %>
       </td>
      <% end %>
      </tr>
     </tbody>
    </table>
   <!--コメント一覧-->
    <div id="book_comment">
     <%= render partial: 'book_comments/book_comment', locals: {book: @book} %>
    </div>
   <!--コメントフォーム-->
    <div class="new-comment">
     <%= render partial: 'book_comments/new_comment', locals: {book: @book, book_comment: @book_comment} %>
      </div>
     </div>
   </div>
  </div>

app/views/favorites/_favorite.html.erb
 <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete, remote: true, data: {"turbolinks" => false}, class: 'text-danger' do %>
      ♥<%= book.favorites.count %>
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book), method: :post, remote: true, data: {"turbolinks" => false} do %>
      ♡<%= book.favorites.count %>
    <% end %>
  <% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {book: @book}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {book: @book}) %>");

app/views/homes/about.html.erb
<div class="container">
 <div class="row">
  <h1 class="px-3 mx-auto">
   Welcome to
   <i class="fas fa-book"></i>
   <strong>Bookers</strong>!
  </h1>
 </div>
</div>

app/views/homes/top.html.erb
<div class="container" >
 <div class="row" >
  <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
   <h1>
    welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!
   </h1>
   <p>
    In <i class="fas fa-book"></i><strong>Bookers</strong>,<br/>
   </p>
   <p>
    you can share and exchange your opinions , inpressions , and emotions<br/>
   </p>
   <p>
    about various books!
   </p>

  <!--ログインページへのリンク-->
  <div class="btn-top mx-auto col-10">
   <button class="btn btn-info btn-sm btn-block mb-3" type="button">
    <%= link_to "Log in", new_user_session_path, class:'text-light' %>
   </button>
  <!--サインアップへのリンク-->
   <button class="btn btn-success btn-sm btn-block" type="button">
    <%= link_to "Sign Up", new_user_registration_path, class:'text-light' %>
   </button>
   </div>
  </div>
 </div>
</div>

app/views/searches/search.html.erb
<% if @range == 'User' %>
 <h2>User search for "<%= @word %>"</h2>
 <table class="table">
  <thead>
   <tr>
    <th>image</th>
    <th>name</th>
    <th></th>
   </tr>
  </thead>
  <tbody>
   <% @users.each do |user| %>
    <tr>
     <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'50x50' %></td>
     <td><%= user.name%></td>
     <td><%= link_to "Show", user_path(user) %></td>
    </tr>
   <% end %>
   </tbody>
  </table>

 <% else %>
  <h2>Book search for "<%= @word %>"</h2>
　<table class="table">
   <thead>
    <tr>
     <th></th>
     <th>Title</th>
     <th>Opinion</th>
     <th></th>
    </tr>
   </thead>
   <% @books.each do |book| %>
   <tbody>
    <tr>
     <td>
      <%= link_to(book.user) do %>
      <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'50x50' %>
      <% end %>
     </td>
     <td>
      <%= link_to  book_path(book) do %>
       <%= book.title %>
      <% end %>
     </td>
     <td><%= book.body %></td>
     </tr>
    </tbody>
    <% end %>
   </table>
<% end %>

app/views/users/edit.html.erb
<!--エラーメッセージ-->
<%= render 'layouts/error', book: @user %>

<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h1>User info</h1>

   <%= form_with model:@user, local:true do |f| %>
   <div class="form-group">
   <!--名前の編集-->
    <label for="inputName">Name</label><br/>
    <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
   </div>
   <div class="form-group">
   <!--トプ画の編集-->
    <label for="inputImage">Image</label><br/>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
   </div>
    <!--自己紹介編集-->
   <div class="form-group">
    <label for="inputIntroduction">Introduction</label><br/>
    <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", placeholder:"自己紹介"%>
   </div>
   <div class="form-group">
    <%= f.submit "Update User", class:'btn btn-secondary text-light', type:'submit' %>
   </div>
   <% end %>
  </div>
 </div>
</div>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
<% if @users.empty? %>
 <p>ユーザーはいません</p>

<% else %>
 <% @users.each do |user| %>
  <table class="table" >
   <thead>
    <tr>
     <th>image</th>
     <th>name</th>
     <th></th>
     <th></th>
     <th></th>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
     </td>
     <td><%= user.name %></td>
     <td>フォロー数:<%= user.followers.count %></td>
     <td>フォロワー数:<%= user.followings.count %></td>
     <td><%= link_to "Show", user_path(user.id) %></td>
    </tr>
   </tbody>
  </table>
 <% end %>
<% end %>

app/views/users/follows.html.erb
<h2>Follow Users</h2>
<% if @users.empty? %>
 <p>ユーザーはいません</p>
<% else %>
 <% @users.each do |user| %>
  <table class="table" >
   <thead>
    <tr>
     <th>image</th>
     <th>name</th>
     <th></th>
     <th></th>
     <th></th>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
      <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
     </td>
     <td><%= user.name %></td>
     <td>フォロー数:<%= user.followers.count %></td>
     <td>フォロワー数:<%= user.followings.count %></td>
     <td><%= link_to "Show", user_path(user.id) %></td>
    </tr>
   </tbody>
  </table>
 <% end %>
<% end %>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
 <!--部分テンプレ-->
  <div class="col-md-3">
   <%= render 'layouts/info', user: @user %>
   <%= render 'layouts/new', new: @new %>
  </div>

 <!--ユーザー一覧-->
  <div class="col-md-8 offset-md-1">
   <h2>Users</h2>
   <table class="table" >
    <thead>
     <tr>
      <th>
       image
      </th>
      <th>
       name
      </th>
      <th>

      </th>
     </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
     <tr>
     <!--トプ画-->
      <td>
       <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
      </td>
     <!--ユーザーネーム-->
      <td>
       <%= user.name %>
      </td>
      <!--フォロー数-->
      <td>
       フォロー数:<%= user.followers.count %>
      </td>
      <!--フォロワー数-->
      <td>
       フォロワー数:<%= user.followings.count %>
      </td>
      <!--フォローボタン-->
      <td>
       <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
         <p>
          <%=link_to "フォローを外す", user_relationships_path(user), method: :delete %></p>
        <% else %>
         <p><%=link_to "フォローする", user_relationships_path(user), method: :post %></p>
        <% end %>
       <% end %>
      </td>
     <!--マイページへのリンク-->
      <td>
       <%= link_to "Show", user_path(user.id) %>
      </td>
     </tr>
     <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
 <!--部分テンプレ-->
  <div class="col-md-3">
   <%= render 'layouts/info', user: @user %>
   <%= render 'layouts/new', new: @new %>
  </div>
  <div class="col-md-8 offset-md-1">
 <!--ユーザー毎の投稿一覧-->
   <h2>Books</h2>
   <table class="table" >
    <thead>
     <tr>
      <th>

      </th>
      <th>Title</th>
      <th>Opinion</th>
     </tr>
    </thead>

    <tbody>
    <% @books.each do |book| %>
     <tr>
      <td>
       <%= link_to user_path(book.user_id) do %>
        <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
       <% end %>
      </td>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
      <!--コメント数-->
      <td>
       <p><%= link_to "コメント数:#{book.book_comments.count}", book_path(book.id) %></p>
      </td>
     </tr>
    <% end %>
    </tbody>
   </table>
   <%= paginate @books %>
  </div>
 </div>
</div>