config/routes.rb
Rails.application.routes.draw do
  get 'search' => 'searches#search'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end



  validates :title, presence: true
  validates :body, presence: true, length: { maximum:200 }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # nameのバリデーション
  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :followed_id, dependent: :destroy
  has_many :followings, through: :passive_relationships, source: :follower

  def followed_by?(user)
      passive_relationships.find_by(follower_id: user.id).present?
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end


  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # ログイン前はトップページ以外にアクセスしてもログイン画面にリダイレクト
  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  # ログイン後に遷移するpathを設定
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

Refile.secret_key = '003673c3dbee64d7fc711edde3f618b7b4b59edf5c301ec65c524a58ac53a648da9676152ce4aa79c7b124ca99237683502191a19a9cbc005527101887947906'

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @user = User.find(current_user.id)
    @new = Book.new
    @books = Book.all
  end

  def show
    @new = Book.new
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @book_comment = BookComment.new
  end

  def create
    @new = Book.new(book_params)
    @new.user_id = current_user.id
    if @new.save
  # 投稿詳細へリダイレクト
    redirect_to book_path(@new), notice: 'You have created book successfully.'
    else
    @user = User.find(current_user.id)
    @books = Book.all
    render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

   def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    # 投稿詳細ページへのリンク
    redirect_to book_path(@book), notice: 'You have updated book successfully.'
    else
     render :edit
    end
   end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    # 投稿一覧にリンク
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
   @range = params[:range]
   @word = params[:word]
  if @range == "User"
     @users = User.looks(params[:search], params[:word])
  else
     @books = Book.looks(params[:search], params[:word])
  end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @new = Book.new
    @books = @user.books.page(params[:page]).reverse_order
  end

  def index
   @users = User.all
   @user = User.find(current_user.id)
   @new = Book.new
  end

   def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user.id)
    end
   end

   def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    # マイページへのリンク
     redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
     render :edit
    end
   end

   def follows
    user = User.find(params[:id])
    @users = user.followers
   end

   def followers
    user = User.find(params[:id])
    @users = user.followings
   end

   private

   def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error.html.erb
<!--エラーメッセージ-->
<div class="text-danger">
 <% if book.errors.any? %>
 <h2><%= book.errors.count %>errors prohibited this obj from being saved:</h2>
 <% book.errors.full_messages.each do |message| %>
 <ul>
  <li><%= message %></li>
 </ul>
 <% end %>
 <% end %>
</div>

app/views/layouts/_info.html.erb
<h2>User info</h2>
 <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
<table class="table" >
 <tbody>
  <tr>
   <th>name</th>
   <td><%= user.name %></td>
  </tr>
  <tr>
   <th>introduction</th>
   <td><%= user.introduction %></td>
  </tr>
  <tr>
   <th>follows</th>
   <td>
    <%= link_to follows_user_path(user) do %>
     <%= user.followers.count %>
    <% end %>
   </td>
  </tr>
  <tr>
   <th>followers</th>
    <td>
     <%= link_to followers_user_path(user) do %>
      <%= user.followings.count %>
     <% end %>
    </td>
  </tr>
 </tbody>
</table>

<!--プロフィール編集へのリンク-->
<% if user == current_user %>
 <%= link_to edit_user_path(user) do %>
  <button type="button" class="btn btn-outline-secondary btn-block btn-sm">
  <i class="fas fa-user-cog"></i>
  </button>
 <% end %>

<% else %>
 <% if user.followed_by?(current_user) %>
  <p>
   <%=link_to user_relationships_path(user), method: :delete do %>
    <button type="button" class= "btn btn-info btn-sm">
     フォローを外す
    </button>
   <% end %>
  </p>
 <% else %>
   <p>
    <%=link_to user_relationships_path(user), method: :post do %>
     <button type="button" class= "btn btn-success btn-sm">
      フォローする
     </button>
    <% end %>
   </p>
 <% end %>
<% end %>

app/views/layouts/_new.html.erb
<!--新規投稿フォーム-->
<h2 class="mt-3">New book</h2>
<%= form_with model: new, local:true do |f| %>
<div class="form-group" >
 <label for="book_title">Title</label><br/>
 <%= f.text_field :title %>
</div>
<div class="form-group" >
 <label for="book_opinion">Opinion</label></br>
 <%= f.text_area :body %><br/>
 </div>
<div class="form-group" >
 <%= f.submit 'Create Book',class:'btn btn-success text-light', type:'submit' %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
  <title>Bookers2Ver2</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script src="https://kit.fontawesome.com/7fd8ce2d95.js" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 </head>

 <body>
  <header>
   <nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Bookers</a>

    <% if user_signed_in? %>
    <ul class="nav justify-content-end">
    <!--マイページ画面へのリンク-->
     <li class="nav-item">
      <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
       <i class="fas fa-home"></i>Home
      <% end %>
     </li>
    <!--ユーザー一覧画面へのリンク-->
     <li class="nav-item">
      <%= link_to users_path, class: 'nav-link text-light' do %>
       <i class="fas fa-users"></i>Users
      <% end %>
     </li>
    <!--一覧画面へのリンク-->
     <li class="nav-item">
      <%= link_to books_path, class: 'nav-link text-light' do %>
       <i class="fas fa-book-open"></i>Books
      <% end %>
     </li>
    <!--トップ画面へのリンク-->
     <li class="nav-item">
      <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
       <i class="fas fa-sign-out-alt"></i>logout
      <% end %>
     </li>
    </ul>

    <% else %>
    <ul class="nav justify-content-end">
    <!--トップ画面へのリンク-->
     <li class="nav-item">
      <%= link_to root_path, class: 'nav-link text-light' do  %>
       <i class="fas fa-home"></i>Home
      <% end %>
     </li>
    <!--アバウトページへのリンク-->
     <li class="nav-item">
      <%= link_to home_about_path, class: 'nav-link text-light' do %>
       <i class="fas fa-link"></i>About
      <% end %>
     </li>
    <!--サインアップ画面へのリンク-->
     <li class="nav-item">
      <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
       <i class="fas fa-user-plus"></i>sign up
      <% end %>
     </li>
    <!--ログイン画面へのリンク-->
     <li class="nav-item">
      <%= link_to user_session_path, class: 'nav-link text-light' do %>
       <i class="fas fa-sign-in-alt"></i>login
      <% end %>
     </li>
    </ul>
   <% end %>
   </nav>
  </header>
   
  <div class="text-success" >
   <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
   <% end %>
  </div>
  
  <main>
  <!--検索フォーム-->
   <div class="text-center">
    <% if user_signed_in? %>
     <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backword_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索" %>
     <% end %>
    <% end %>
  </div>

  <%= yield %>
 </main>
 
 <div class="container mt-5" >
  <div class="row">
   <div class="mx-auto">
    <footer class="p-auto">CopyRight Infratop.inc</footer>
   </div>
  </div>
 </div>

</body>

</html>